global:
  scrape_interval: 15s           # How often to scrape targets by default
  scrape_timeout: 10s            # Timeout for scraping targets
  evaluation_interval: 1m        # How often to evaluate rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093        # Alertmanager service address

rule_files:
  - /etc/prometheus/alert_rules.yml  # Rule files for alerts

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrape Prometheus itself

  - job_name: 'node'
    static_configs:
      - targets: ['Ip-of-targeted-server:9100']
        labels:
          alias: 'javaapis-prod'
      - targets: ['Ip-of-targeted-server:9100']
        labels:
          alias: 'chat-prod'
      - targets: ['Ip-of-targeted-server:9100']
        labels:
          alias: 'web-prod'
      - targets: ['Ip-of-targeted-server:9100']
        labels:
          alias: 'db-prod'
      - targets: ['Ip-of-targeted-server:9100']
        labels:
          alias: 'app-prod'
    relabel_configs:
      - source_labels: [alias]
        target_label: instance    # Relabel instance names based on alias

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['18.216.80.50:8085']
        labels:
          alias: 'javaapis-prod'
      - targets: ['3.137.20.105:8085']
        labels:
          alias: 'chat-prod'
      - targets: ['3.128.41.41:8085']
        labels:
          alias: 'web-prod'
      - targets: ['3.16.171.11:8085']
        labels:
          alias: 'app-prod'
      - targets: ['3.15.128.75:8050']
        labels:
          alias: 'db-prod'
    relabel_configs:
      - source_labels: [alias]
        target_label: instance    # Relabel instance names based on alias

  - job_name: 'web_check'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a 2xx response
    static_configs:
      - targets:
        - https://app.xyz.com/login
        - https://www.xyz.com/
        - https://backofficeapi.xyz.com/
        - https://backoffice.xyz.com/
        - https://api.xyz.com/api
        - https://chat.xyz.com/health/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [__param_target]
        target_label: instance

